#ifndef _SMP_SMART_BASKET_H
#define _SMP_SMART_BASKET_H

// D0 (GPIO16) - On-board LED
// D1 - I2C's SCL
// D2 - I2C's SDA
// D3 (GPIO0) - FLASH
#define SMP_LED0 D0
#define SMP_LED1 D4
#define SMP_FEATHERBOARD_PIN 10
#define SMP_PHOTO_DIODE_0_PIN D5
#define SMP_CUSTOM_BUTTON_0_PIN D6
#define SMP_CUSTOM_BUTTON_1_PIN D7
// D8 (GPIO15)

#define SMP_PACKET_TYPE_BASKET             0x00
#define SMP_PACKET_TYPE_ACCELEROMETER_DATA 0x01
#define SMP_PACKET_TYPE_CUSTOM_BUTTON      0x02
#define SMP_PACKET_TYPE_PEOPLE_DETECTED    0x03

#endif // _SMP_SMART_BASKET_H
